# This is a basic workflow that is manually triggered

name: bing rewards manual trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BING_REWARDS_USER: ${{ secrets.BING_REWARDS_USER }}
      BING_REWARDS_PASSWORD: ${{ secrets.BING_REWARDS_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Collect Bing Rewards Points
      run: docker run -e BING_REWARDS_USER="${BING_REWARDS_USER}" -e BING_REWARDS_PASSWORD="${BING_REWARDS_PASSWORD}" leandrorosa/bing-rewards:latest
